### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Bram91** [Runemoro/better-renderer#1]
Just tried the plugin on my windows system, after waiting for about 5minutes after enabling the plugin(Still on the `Downloading game cache, this may take a few minutes` stage) The following exceptions occur:
```
2020-11-08 11:09:36 [Client] WARN  n.r.client.callback.ClientThread - Exception in invoke
java.lang.RuntimeException: 65544: WGL: Failed to set selected pixel format: The pixel format is invalid. 
	at renderer.plugin.BetterRendererPlugin.lambda$init$1(BetterRendererPlugin.java:154)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPP(Native Method)
	at org.lwjgl.glfw.GLFWNativeWin32.glfwAttachWin32Window(GLFWNativeWin32.java:143)
	at renderer.plugin.JawtContextWindows.<init>(JawtContextWindows.java:23)
	at renderer.plugin.JawtContext.create(JawtContext.java:26)
	at renderer.plugin.BetterRendererPlugin.init(BetterRendererPlugin.java:157)
	at net.runelite.client.callback.ClientThread.lambda$invoke$0(ClientThread.java:48)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:191)
	at lv.qb(lv.java:38201)
	at client.ak(client.java)
	at ba.d(ba.java:361)
	at ba.run(ba.java:315)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-11-08 11:09:36 [Client] ERROR client-patch - Game crash: null
java.lang.NullPointerException: null
	at renderer.plugin.BetterRendererPlugin.draw(BetterRendererPlugin.java:235)
	at client.rx(client.java:41655)
	at hz.ql(hz.java:985)
	at ef.cg(ef.java)
	at fu.xi(fu.java:10342)
	at bv.gs(bv.java:4616)
	at ax.ik(ax.java:9441)
	at kv.io(kv.java:9330)
	at client.zv(client.java:4263)
	at client.ak(client.java:1621)
	at ba.d(ba.java:361)
	at ba.run(ba.java:315)
	at java.base/java.lang.Thread.run(Unknown Source)
```
Running the pluginhub version `8b3e5be0d9e07074e08ffacf68273ca06b859194` on the release client.

**Comment by Runemoro** [comment]
Fixed in [1.3](https://github.com/runelite/plugin-hub/pull/754)
