### ISSUE TITLE
Plugin does not turn on anymore. 

### ISSUE THREAD

**Issue by zeakzz** [Runemoro/better-renderer#8]
It stays at saying "downloading game cache, this may take a few minutes" and never actually turns on.

**Comment by Runemoro** [comment]
Could you send me your client log?

**Comment by Cyborger1** [comment]
It says "downloading cache", then the screen flashes black for one frame and it turns off. This is printed to the log:

```
2020-11-14 23:09:45 [Client] WARN  n.r.client.callback.ClientThread - Exception in invoke
java.lang.NoSuchMethodError: java.nio.IntBuffer.rewind()Ljava/nio/IntBuffer;
	at org.lwjgl.opengl.awt.PlatformWin32GLCanvas.create(PlatformWin32GLCanvas.java:523)
	at org.lwjgl.opengl.awt.PlatformWin32GLCanvas.create(PlatformWin32GLCanvas.java:156)
	at renderer.plugin.BetterRendererPlugin.init(BetterRendererPlugin.java:177)
	at net.runelite.client.callback.ClientThread.lambda$invoke$0(ClientThread.java:48)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:191)
	at lv.qb(lv.java:38201)
	at client.ak(client.java)
	at ba.d(ba.java:361)
	at ba.run(ba.java:315)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Runemoro** [comment]
Fixed in the latest version.
